baseURL = "https://doc.t98.info/"
publishDir = "docs"
languageCode = "ja-jp"
theme = "minimal-bootstrap-hugo-theme"
title = "ほむりんルーム総合インフォ"
subtitle = "サイトのお知らせを掲載いたします。"
hasCJKLanguage = true

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
  description = "サイトのお知らせを掲載いたします。"
  contentBackgroundColor = "#fff"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "800px"
  customDateFormat = "2006-01-02 15:04:05"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = true
  googleAnalytics = ""
  cookieConsent = false
  includeBootstrapJs = true
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "タグ"
  url = "/tags/"
  weight = 1
  [[menu.nav]]
  name = "カテゴリ"
  url = "/categories/"
  weight = 2
  [[menu.nav]]
  name = "About"
  url = "/about/"
  weight = 3
  [[menu.nav]]
  name = "RSS"
  url = "/index.xml"
  weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2